# Action Cable uses Redis to administer connections, channels, and sending/receiving messages over the WebSocket.
production:
  adapter: redis
  url: <%= ENV['REDISTOGO_URL'] %>

development:
  adapter: redis
  url: redis://localhost:6379/2

test:
  url: async
